package org.keycloak.quickstart.bpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApprovalRequest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ApprovalRequest() {
    }

}